### ISSUE TITLE
Error with Mendix 7.13.1 : DEPRECATED: mendix.lang.null Exec. Use plain javascript if instead -- will be removed in version:9.0.

### ISSUE THREAD

**Issue by sjorsschultz** [ChrisdeG/DropZone#19]
Hi all,

We're seeing a warning in the console after an upgrade to 7.13.1:

Error with Mendix 7.13.1 : DEPRECATED: mendix.lang.null Exec. Use plain javascript if instead -- will be removed in version:9.0.

Is there possibly an update available to solve these warnings? Have upgraded to latest version 4.0.3 but to no avail..

Cheers,
Sjors

**Comment by ChrisdeG** [comment]
New version 4.0.4 is available

**Comment by sjorsschultz** [comment]
Thank you Chris!
