### ISSUE TITLE
Dropzone widget seems not working in version 7.14.1

### ISSUE THREAD

**Issue by Wietjerr** [ChrisdeG/DropZone#20]
Hi Chris, 

Is there a new widget version for the latest version of Mendix (7.14.1)?
They have changed the client logging in the newest versions of Mendix and the widget cannot handle this i think.
There goes something wrong like a 'TypeError: Converting circular structure to JSON' at r70 of the dropzone.js

Kind regards,
Wieger Kloppenburg

**Comment by armandojacobus** [comment]
Same here.

**Comment by ChrisdeG** [comment]
Do you have more information? I can not reproduce the issue, but worse the client logging is completely broke in 14.1.

**Comment by ChrisdeG** [comment]
I have disabled all logging and it works again, must be a bug in sending the logs to the client

**Comment by Narev** [comment]
Chris was it all logging, or just that line where you logged logger.debug('this', this);? I thought that this might trigger a infinit loop.

**Comment by ChrisdeG** [comment]
Pieter, I agree that one is suspect but I am not sure. Maybe all logged objects may cause this. Testing gave ambiguous results.
