### ISSUE TITLE
Adding a lot of pictures at the same time gives errors

### ISSUE THREAD

**Issue by ADoppenberg** [ChrisdeG/DropZone#25]
Hi Chris,

We have the dropzone widget installed in a project and it works great so far, only we have one issue. When uploading multiple photo's at the same time it often occurs multiple are rejected and a few succeed. This only happens when we upload it for the first time. If we upload the pictures again they all succeed. We would like that the uploading succeeds the first time and users don't have to perform it twice. In the log we get a Failed to commit message and after that a nullpointerexception for each photo that failed. 

So for instance I upload 7 pictures it could be the case that 5 fail and 2 succeed. The log gives 10 error log messages. 5 failed to commit and 5 nullpointerexception. We use the latest version of the widget and are using mendix version 7.17.2. I hope you could help us on this matter.

Kind Regards,
Alwin Doppenberg

**Comment by TobiasHankeOC** [comment]
Hey, this is now reported several times by using different words.
I posted a bit more analyse on this here on issue "Duplicate column value violates its unique constraint".
Basically it stumbles over itself on commit as it tries to autocommit the linked parent
commiting the parent before, worked for me as a workaround for this (as this is also the reason why it suddenly works afterwards, as it is then autocommited)

**Comment by ChrisdeG** [comment]
The problem with the issues is that it never happened in previous versions of Mendix and I have little time to work on it. Maybe Mendix can help in this case.

**Comment by ADoppenberg** [comment]
Thank you both for your responses! Tobias your workaround works also great for me, thank you for proposing the this, I didn't know this was the underlying problem.

**Comment by ChrisdeG** [comment]
Can you please test https://github.com/ChrisdeG/DropZone/releases/download/4.0.6/DropZone.mpk
