### ISSUE TITLE
Application breaks after implementing the widget

### ISSUE THREAD

**Issue by sebasvanderplaat** [ChrisdeG/DropZone#3]
Hi, Just downloaded the widget from the app store. In Mx 6.01, my app doesn't work anymore when i implement the widget. It gives me a blank screen only.

**Comment by ChrisdeG** [comment]
Hi Sebas,



Download release 3.0 from github, it is published soon.
https://github.com/ChrisdeG/DropZone/releases/download/V3.0/DropZone.mpk



Met vriendelijke groet,





[image: FlowFabric] <http://www.flowfabric.com/>



Chris de Gelder

Business Consultant

cdgelder@flowfabric.com

+31(0)6 - 461 39 865



*Van:* sebasvanderplaat [mailto:notifications@github.com]
*Verzonden:* Tuesday, January 5, 2016 10:03 AM
*Aan:* ChrisdeG/DropZone
*Onderwerp:* [DropZone] Application breaks after implementing the widget
(#3)



Hi, Just downloaded the widget from the app store In Mx 601, my app doesn't
work anymore when i implement the widget It gives me a blank screen only

—
Reply to this email directly or view it on GitHub
<https://github.com/ChrisdeG/DropZone/issues/3>.[image: Afbeelding
verwijderd door afzender.]
