### ISSUE TITLE
Widget on Mendix 5.21

### ISSUE THREAD

**Issue by Joris990** [ChrisdeG/DropZone#6]
Hi, anybody else having trouble with this widget on Mx 5.21? 
Our current app is on Mx 5.21 and we run into compatability issues with IOS and IE (11), even after updating the dropzonejs lib. Should we update to Mx 6?

Thnx!

**Comment by nvwieren** [comment]
Can you be more specific on what compatibility issue you are running into?

**Comment by ChrisdeG** [comment]
I have improved the widget and it running on IOS. Github is not updated yet.

**Comment by keilt** [comment]
Hi Chris, great to hear that you already have an improved version. Do you already plan to update Github?
